### ISSUE TITLE
dalao，PHP环境怎么安装能说一下吗

### ISSUE THREAD

**Issue by shilohooo** [lonisy/data-dictionary#4]

**Comment by shilohooo** [comment]
需要的是运行环境还是开发环境？

**Comment by lonisy** [comment]
一般用在开发环境。
PHP开发环境可参考XAMPP、PhpStudy、Wamp Server 集成工具。
亦可自行安装、
Windows 环境需要去PHP MySQL 网站下载对应的安装包。
Centos 可用 yum 安装。
Ubuntu 可用 apt-get 安装。
MAC 可用 brew 安装。

XAMPP 参考资料 https://www.apachefriends.org/index.html
PhpStudy 参考资料 https://www.xp.cn/
Wamp Server 参考资料 http://www.wampserver.com/en/

**Comment by shilohooo** [comment]
tks:)
